language: php
php:
  - 5.5
  - 5.6
  - 7.0
matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: deps="low"
before_script:
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require --no-update "phpunit/phpunit:${PHPUNIT_VERSION}"; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" = "" ]; then composer install; fi
script: vendor/bin/phpunit
